In [1]:
import pandas as pd

In [10]:
data = {'name': ["sudh","krish","hitesh", "telusko" ],
       "salary":[100,200,300,400],
       "mail_id":["sudanshu@ineuron.ai","krish@ineuron.ai","hitesh@ineuron.ai","telusko@ineuron.ai"],
       "addr":['bir',"bir","bir","mum"]
       
       }

In [35]:
pd.DataFrame(data,)

name  salary              mail_id addr
0     sudh     100  sudanshu@ineuron.ai  bir
1    krish     200     krish@ineuron.ai  bir
2   hitesh     300    hitesh@ineuron.ai  bir
3  telusko     400   telusko@ineuron.ai  mum

In [36]:
df =pd.DataFrame(data)

In [20]:
df.loc[5:6]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  bir
6  hitesh     300  hitesh@ineuron.ai  bir

name  salary             mail_id addr
5    krish     200    krish@ineuron.ai  bir
6   hitesh     300   hitesh@ineuron.ai  bir
7  telusko     400  telusko@ineuron.ai  mum

In [28]:
data1 = {"pf_num":[234,47,4596,4624],
         "income_tax":[455,57472,6973,77465],
         "mobile_no":[4454,674,672,68768],
         "courses":["ds",'bigdata',"web dev","blockchain"]
    
}

In [30]:
df1 =pd.DataFrame(data1)

In [31]:
df1

pf_num  income_tax  mobile_no     courses
0     234         455       4454          ds
1      47       57472        674     bigdata
2    4596        6973        672     web dev
3    4624       77465      68768  blockchain

In [32]:
#concationation operation

In [37]:
pd.concat([df,df1])

name  salary              mail_id addr  pf_num  income_tax  mobile_no  \
0     sudh   100.0  sudanshu@ineuron.ai  bir     NaN         NaN        NaN   
1    krish   200.0     krish@ineuron.ai  bir     NaN         NaN        NaN   
2   hitesh   300.0    hitesh@ineuron.ai  bir     NaN         NaN        NaN   
3  telusko   400.0   telusko@ineuron.ai  mum     NaN         NaN        NaN   
0      NaN     NaN                  NaN  NaN   234.0       455.0     4454.0   
1      NaN     NaN                  NaN  NaN    47.0     57472.0      674.0   
2      NaN     NaN                  NaN  NaN  4596.0      6973.0      672.0   
3      NaN     NaN                  NaN  NaN  4624.0     77465.0    68768.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [38]:
pd.concat([df,df1], axis=1)

name  salary              mail_id addr  pf_num  income_tax  mobile_no  \
0     sudh     100  sudanshu@ineuron.ai  bir     234         455       4454   
1    krish     200     krish@ineuron.ai  bir      47       57472        674   
2   hitesh     300    hitesh@ineuron.ai  bir    4596        6973        672   
3  telusko     400   telusko@ineuron.ai  mum    4624       77465      68768   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [39]:
data2 = {'0': ["sudh","krish","hitesh", "telusko" ],
       "1":[100,200,300,400],
       "2":["sudanshu@ineuron.ai","krish@ineuron.ai","hitesh@ineuron.ai","telusko@ineuron.ai"],
       "3":['bir',"bir","bir","mum"]
       
       }

In [40]:
data3 = {"0":[234,47,4596,4624],
         "1":[455,57472,6973,77465],
         "2":[4454,674,672,68768],
         "3":["ds",'bigdata',"web dev","blockchain"]
    
}

In [42]:
df2 = pd.DataFrame(data2)

In [44]:
df3= pd.DataFrame(data3)

In [47]:
pd.concat([df2,df3] )

0      1                    2           3
0     sudh    100  sudanshu@ineuron.ai         bir
1    krish    200     krish@ineuron.ai         bir
2   hitesh    300    hitesh@ineuron.ai         bir
3  telusko    400   telusko@ineuron.ai         mum
0      234    455                 4454          ds
1       47  57472                  674     bigdata
2     4596   6973                  672     web dev
3     4624  77465                68768  blockchain

In [48]:
pd.concat([df2,df3] , axis=1)

0    1                    2    3     0      1      2           3
0     sudh  100  sudanshu@ineuron.ai  bir   234    455   4454          ds
1    krish  200     krish@ineuron.ai  bir    47  57472    674     bigdata
2   hitesh  300    hitesh@ineuron.ai  bir  4596   6973    672     web dev
3  telusko  400   telusko@ineuron.ai  mum  4624  77465  68768  blockchain

In [49]:
data4 = {"emp_id":[101,102,103,104],
         "salary":[234,345,200,400],
         "pf":[23,34,56,78]
    
    
}

In [57]:
data5 = {"emp_id":[101,102,104,105],
        "mob_no":[3455,5656,767,878],
        "house_nu":[345,345,345,56]
        }

In [58]:
 df4 = pd.DataFrame(data4)

In [59]:
df5 = pd.DataFrame(data5)

In [66]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [65]:
df5

emp_id  mob_no  house_nu
0     101    3455       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [62]:
pd.merge(df4,df5, how = "left")

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3455.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [63]:
pd.merge(df4,df5, how = "right")

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3455       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [64]:
pd.merge(df4,df5 , how = "right", on = "emp_id")

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3455       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [68]:
data6 = {"emp_id1":[101,102,103,104],
         "salary":[234,345,200,400],
         "pf":[23,34,56,78]
    
    
}

data7 = {"emp_id2":[101,102,104,105],
        "mob_no":[3455,5656,767,878],
        "house_nu":[345,345,345,56]
        }

In [69]:
df6 = pd.DataFrame(data6)

In [70]:
df7 = pd.DataFrame(data7)

In [71]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [72]:
df7

emp_id2  mob_no  house_nu
0      101    3455       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [74]:
pd.merge(df6,df7 , left_on= "emp_id1", right_on= "emp_id2")

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3455       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [82]:
data8 = {"emp_id":[101,102,103,104],
         "salary":[234,345,200,400],
         "pf":[23,34,56,78]
    
    
}

data9 = {"emp_id":[101,102,104,105,123],
        "salary":[234,345,200,878,43],
        "house_nu":[345,345,345,56,234]
        }

In [76]:
df8 = pd.DataFrame(data8)

In [83]:
df9 = pd.DataFrame(data9)

In [84]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [85]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56
4     123      43       234

In [86]:
pd.merge(df8,df9, on= ["emp_id", "salary"])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [97]:
data10 = {"emp_id1":[101,102,103,104],
         "salary1":[234,345,200,400],
         "pf":[23,34,56,78]
    
    
}

data11 = {"emp_id2":[101,102,104,105,123],
        "salary2":[234,345,200,878,43],
        "house_nu":[345,345,345,56,234]
        }

In [98]:
df10 = pd.DataFrame(data10, index=["a","b","c","d"])

In [99]:
df11 = pd.DataFrame(data11, index=["a","b","d","e","f"])

In [100]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [101]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [102]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [118]:
df_sales = pd.read_csv("sales_data_final")

FileNotFoundError: [Errno 2] No such file or directory: 'sales_data_final'

In [119]:
import numpy as np

In [120]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [121]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [123]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [125]:
l= [1,2,3,4],[2,3,4,5]

In [126]:
l[0][0]

1

In [130]:
a= np.array([3,4,5,6], ndmin=5)

In [131]:
a

array([[[[[3, 4, 5, 6]]]]])

In [132]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [133]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
arr.ndim

2

In [136]:
np.random.randint(1,10,(4,4,2))

array([[[4, 2],
        [4, 2],
        [6, 7],
        [1, 9]],

       [[2, 3],
        [1, 9],
        [8, 1],
        [3, 6]],

       [[1, 6],
        [1, 6],
        [7, 4],
        [5, 8]],

       [[8, 5],
        [1, 6],
        [7, 1],
        [2, 2]]])

In [137]:
np.random.randint(1,10,(4,4))

array([[5, 8, 8, 9],
       [7, 4, 3, 7],
       [7, 6, 5, 1],
       [8, 4, 3, 1]])

In [143]:
p =np.random.randint(1,10,(25,4,4))

In [144]:
p.ndim

3

In [145]:
p

array([[[3, 2, 3, 6],
        [4, 2, 3, 2],
        [6, 7, 9, 5],
        [9, 5, 3, 7]],

       [[4, 2, 1, 8],
        [9, 6, 5, 4],
        [5, 6, 1, 9],
        [9, 2, 2, 8]],

       [[2, 1, 6, 1],
        [8, 2, 3, 6],
        [6, 3, 1, 8],
        [2, 7, 9, 7]],

       [[8, 6, 4, 4],
        [9, 7, 2, 1],
        [2, 7, 6, 9],
        [8, 1, 3, 2]],

       [[8, 1, 2, 7],
        [5, 2, 1, 7],
        [1, 6, 8, 7],
        [9, 4, 7, 6]],

       [[7, 3, 9, 9],
        [3, 5, 1, 8],
        [5, 4, 5, 9],
        [7, 6, 6, 3]],

       [[6, 8, 2, 9],
        [6, 7, 9, 3],
        [8, 1, 4, 1],
        [4, 6, 9, 3]],

       [[8, 8, 3, 4],
        [5, 3, 6, 7],
        [8, 5, 4, 3],
        [4, 5, 9, 5]],

       [[6, 4, 7, 2],
        [1, 8, 5, 3],
        [5, 7, 9, 6],
        [5, 7, 2, 1]],

       [[6, 4, 4, 8],
        [2, 1, 1, 6],
        [2, 3, 8, 4],
        [5, 9, 4, 9]],

       [[1, 2, 5, 2],
        [8, 5, 4, 8],
        [7, 5, 2, 5],
        [2, 8, 6, 3]],

       [[4